server:
  port: 5999
  
spring:
  application:
   name: auth-server
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/dataprueba
    username: postgres
    password: pgadmin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5761/eureka/

security:
  oauth2:
    client:
      client-id: williamapp
      client-secret: william15code
      authorized-grant-types: password
      scope: read,write